"""Add image_url to certificates

Revision ID: 57941e827e50
Revises: f262252d6456
Create Date: 2026-07-29 00:02:34.047816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57941e827e50'
down_revision: Union[str, None] = 'f262252d6456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'image_url')
    # ### end Alembic commands ###
