"""Upgrade projects model fields

Revision ID: 90bfb4f653cd
Revises: c13c40d2d41b
Create Date: 2026-07-28 22:14:06.373685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '90bfb4f653cd'
down_revision: Union[str, None] = 'c13c40d2d41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slug', sa.String(length=100), nullable=False))
    op.add_column('projects', sa.Column('short_description', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('full_description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('display_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', mysql.TEXT(), nullable=False))
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_column('projects', 'display_order')
    op.drop_column('projects', 'full_description')
    op.drop_column('projects', 'short_description')
    op.drop_column('projects', 'slug')
    # ### end Alembic commands ###
