"""Add profile_image to settings

Revision ID: c13c40d2d41b
Revises: 87cb7a25542c
Create Date: 2026-07-28 21:59:42.314842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13c40d2d41b'
down_revision: Union[str, None] = '87cb7a25542c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('profile_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'profile_image')
    # ### end Alembic commands ###
