"""Replace blogs with resumes table updates

Revision ID: f262252d6456
Revises: 90bfb4f653cd
Create Date: 2026-07-28 23:46:56.321427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f262252d6456'
down_revision: Union[str, None] = '90bfb4f653cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('resumes', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('resumes', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('resumes', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.drop_column('resumes', 'is_active')
    op.drop_column('resumes', 'created_at')
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.drop_column('settings', 'hero_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('hero_image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.add_column('resumes', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('resumes', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'uploaded_at')
    op.drop_column('resumes', 'mime_type')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'file_name')
    # ### end Alembic commands ###
